"""Dependency-free emitters for TOML/JSON/YAML.

These helpers serialize the in-memory config dict into user-facing formats
without pulling in third-party libraries. The TOML/YAML emitters are
purpose-built for this project's schema and intentionally conservative:
 - Skip empty/None values to keep files tidy
 - Preserve simple types (bool/int/float/str) and basic collections
 - Render provider/profile sections explicitly
 - Keep whitespace stable and collapse excess blank lines

For complex cases we prefer shaping the dict in ``render.py`` so that all
emitters remain in parity.
"""

from __future__ import annotations
import json
import re
from typing import Dict, List


def to_toml(cfg: Dict) -> str:
    """Serialize ``cfg`` to TOML tailored to the Codex schema.

    Notes
    - Omits empty/None fields; includes only meaningful values.
    - Emits tables for ``[tui]``, ``[history]``, ``[sandbox_workspace_write]``,
      and nested provider/profile sections.
    - Renders JSON-compatible scalars using ``json.dumps`` to avoid quoting
      issues for strings.
    - Stable formatting with at most single blank lines between sections.
    """

    def is_empty(v) -> bool:
        if v is None:
            return True
        if isinstance(v, str):
            return v.strip() == ""
        if isinstance(v, (list, dict)):
            return len(v) == 0
        return False

    lines: List[str] = []
    lines.append("# Generated by codex-cli-linker")

    def w(key: str, val):
        if key == "tui":
            return
        if is_empty(val):
            return
        if isinstance(val, bool):
            sval = "true" if val else "false"
        elif isinstance(val, (int, float)):
            sval = str(val)
        else:
            sval = json.dumps(val)
        lines.append(f"{key} = {sval}")

    w("model", cfg.get("model"))
    w("model_provider", cfg.get("model_provider"))
    w("approval_policy", cfg.get("approval_policy"))
    w("sandbox_mode", cfg.get("sandbox_mode"))
    w("file_opener", cfg.get("file_opener"))
    w("model_reasoning_effort", cfg.get("model_reasoning_effort"))
    w("model_reasoning_summary", cfg.get("model_reasoning_summary"))
    w("model_verbosity", cfg.get("model_verbosity"))
    w("model_context_window", cfg.get("model_context_window"))
    w("model_max_output_tokens", cfg.get("model_max_output_tokens"))
    w("project_doc_max_bytes", cfg.get("project_doc_max_bytes"))
    # TUI table
    tui_cfg = cfg.get("tui") or {}
    if isinstance(tui_cfg, dict) and (
        tui_cfg.get("style") or ("notifications" in tui_cfg)
    ):
        lines.append("")
        lines.append("[tui]")
        if tui_cfg.get("style"):
            lines.append("style = " + json.dumps(tui_cfg["style"]))
        if "notifications" in tui_cfg:
            nv = tui_cfg.get("notifications")
            if isinstance(nv, list):
                arr = ", ".join(json.dumps(x) for x in nv)
                lines.append(f"notifications = [ {arr} ]")
            elif isinstance(nv, bool):
                lines.append("notifications = " + ("true" if nv else "false"))
    w("notify", cfg.get("notify"))
    w("instructions", cfg.get("instructions"))
    w("hide_agent_reasoning", cfg.get("hide_agent_reasoning"))
    w("show_raw_agent_reasoning", cfg.get("show_raw_agent_reasoning"))
    w(
        "model_supports_reasoning_summaries",
        cfg.get("model_supports_reasoning_summaries"),
    )
    w("chatgpt_base_url", cfg.get("chatgpt_base_url"))
    w("experimental_resume", cfg.get("experimental_resume"))
    w("experimental_instructions_file", cfg.get("experimental_instructions_file"))
    w(
        "experimental_use_exec_command_tool",
        cfg.get("experimental_use_exec_command_tool"),
    )
    w(
        "responses_originator_header_internal_override",
        cfg.get("responses_originator_header_internal_override"),
    )
    w("preferred_auth_method", cfg.get("preferred_auth_method"))
    w("profile", cfg.get("profile"))
    w("disable_response_storage", cfg.get("disable_response_storage"))

    tools = cfg.get("tools") or {}
    tools_filtered = {k: v for k, v in tools.items() if not is_empty(v)}
    if tools_filtered:
        lines.append("")
        lines.append("[tools]")
        for k, v in tools_filtered.items():
            if isinstance(v, bool):
                lines.append(f"{k} = {'true' if v else 'false'}")
            elif isinstance(v, (int, float)):
                lines.append(f"{k} = {v}")
            else:
                lines.append(f"{k} = {json.dumps(v)}")

    hist = cfg.get("history") or {}
    hist_filtered = {k: v for k, v in hist.items() if not is_empty(v)}
    if hist_filtered:
        lines.append("")
        lines.append("[history]")
        if "persistence" in hist_filtered:
            lines.append(f"persistence = {json.dumps(hist_filtered['persistence'])}")
        if "max_bytes" in hist_filtered:
            lines.append(f"max_bytes = {hist_filtered['max_bytes']}")

    sww = cfg.get("sandbox_workspace_write") or {}
    sww_filtered = {k: v for k, v in sww.items() if not is_empty(v)}
    if sww_filtered:
        lines.append("")
        lines.append("[sandbox_workspace_write]")
        for k, val in sww_filtered.items():
            if isinstance(val, list):
                if not val:
                    continue
                arr = ", ".join(json.dumps(x) for x in val if not is_empty(x))
                if arr.strip():
                    lines.append(f"{k} = [ {arr} ]")
            elif isinstance(val, bool):
                lines.append(f"{k} = {'true' if val else 'false'}")
            elif isinstance(val, (int, float)):
                lines.append(f"{k} = {val}")
            else:
                if not is_empty(val):
                    lines.append(f"{k} = {json.dumps(val)}")

    providers = cfg.get("model_providers") or {}
    for pid, p in providers.items():
        pf = {k: v for k, v in p.items() if not is_empty(v)}
        if "query_params" in pf and is_empty(pf["query_params"]):
            pf.pop("query_params", None)
        if not pf:
            continue
        section_lines = []
        for k in ("name", "base_url", "wire_api", "env_key", "api_key_env_var"):
            if k in pf:
                section_lines.append(f"{k} = {json.dumps(pf[k])}")
        for k in (
            "request_max_retries",
            "stream_max_retries",
            "stream_idle_timeout_ms",
        ):
            if k in pf:
                section_lines.append(f"{k} = {pf[k]}")
        if (
            "query_params" in pf
            and isinstance(pf["query_params"], dict)
            and pf["query_params"]
        ):
            qp_items = ", ".join(
                f"{json.dumps(k)} = {json.dumps(v)}"
                for k, v in pf["query_params"].items()
                if not is_empty(v)
            )
            if qp_items:
                section_lines.append(f"query_params = {{ {qp_items} }}")
        # Optional header maps
        if (
            "http_headers" in pf
            and isinstance(pf["http_headers"], dict)
            and pf["http_headers"]
        ):
            pairs = ", ".join(
                f"{json.dumps(k)} = {json.dumps(v)}"
                for k, v in pf["http_headers"].items()
            )
            section_lines.append(f"http_headers = {{ {pairs} }}")
        if (
            "env_http_headers" in pf
            and isinstance(pf["env_http_headers"], dict)
            and pf["env_http_headers"]
        ):
            pairs = ", ".join(
                f"{json.dumps(k)} = {json.dumps(v)}"
                for k, v in pf["env_http_headers"].items()
            )
            section_lines.append(f"env_http_headers = {{ {pairs} }}")
        if section_lines:
            lines.append("")
            lines.append(f"[model_providers.{pid}]")
            lines.extend(section_lines)

    profiles = cfg.get("profiles") or {}
    for name, pr in profiles.items():
        prf = {k: v for k, v in pr.items() if not is_empty(v)}
        if not prf:
            continue
        section_lines = []
        for k, val in prf.items():
            if isinstance(val, (int, float)):
                section_lines.append(f"{k} = {val}")
            elif isinstance(val, bool):
                section_lines.append(f"{k} = {'true' if val else 'false'}")
            else:
                section_lines.append(f"{k} = {json.dumps(val)}")
        if section_lines:
            lines.append("")
            lines.append(f"[profiles.{name}]")
            lines.extend(section_lines)

    out = "\n".join(lines).strip() + "\n"
    out = re.sub(r"\n{3,}", "\n\n", out)
    return out


def to_json(cfg: Dict) -> str:
    """Serialize ``cfg`` to pretty-printed JSON (2-space indents)."""
    return json.dumps(cfg, indent=2)


def to_yaml(cfg: Dict) -> str:
    """Serialize ``cfg`` to a small subset of YAML.

    This emitter covers dictionaries and lists with scalar values. It is not a
    general-purpose YAML serializer and avoids advanced features (anchors,
    multi-line strings, tags). The output is sufficient for the project's
    configuration needs without introducing third-party dependencies.
    """

    def dump(obj, indent=0):
        sp = "  " * indent
        if isinstance(obj, dict):
            out: List[str] = []
            for k, v in obj.items():
                if isinstance(v, (dict, list)):
                    out.append(f"{sp}{k}:")
                    out.append(dump(v, indent + 1))
                else:
                    out.append(f"{sp}{k}: {json.dumps(v)}")
            return "\n".join(out)
        elif isinstance(obj, list):
            out: List[str] = []
            for v in obj:
                if isinstance(v, (dict, list)):
                    out.append(f"{sp}-")
                    out.append(dump(v, indent + 1))
                else:
                    out.append(f"{sp}- {json.dumps(v)}")
            return "\n".join(out)
        else:
            return f"{sp}{json.dumps(obj)}"

    return dump(cfg) + "\n"


__all__ = ["to_toml", "to_json", "to_yaml"]
