name: Format

on:
  push:
    branches: [main]
    paths-ignore:
      - "coverage.svg"
  pull_request:
    branches: [main]
    paths-ignore:
      - "coverage.svg"

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install black
        run: python -m pip install --upgrade pip "black==24.10.0"
      - name: Black check
        run: python -m black --check .
