name: Release
permissions:
  contents: read

on:
  push:
    tags:
      - "v*" # e.g., v0.1.0
      - "release-*" # e.g., release-2025-09-07
  workflow_dispatch: {}

jobs:
  build_x64:
    name: Build x64 (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install pyinstaller

      - name: Build single-file binary (x64)
        shell: bash
        run: |
          pyinstaller -F -n codex-cli-linker codex-cli-linker.py
          mkdir -p release
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp dist/codex-cli-linker.exe "release/codex-cli-linker-windows-x64.exe"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp dist/codex-cli-linker "release/codex-cli-linker-macos-x64"
          else
            cp dist/codex-cli-linker "release/codex-cli-linker-linux-x64"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ runner.os }}-x64
          path: release/*
          if-no-files-found: error

  build_arm:
    name: Build arm64 (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Windows 11 ARM hosted runner; ensure your repository has access.
        os: [ubuntu-24.04-arm, macos-latest, windows-11-arm]
        py: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install pyinstaller

      - name: Build single-file binary (arm64)
        shell: bash
        run: |
          pyinstaller -F -n codex-cli-linker codex-cli-linker.py
          mkdir -p release
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp dist/codex-cli-linker.exe "release/codex-cli-linker-windows-arm64.exe"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp dist/codex-cli-linker "release/codex-cli-linker-macos-arm64"
          else
            cp dist/codex-cli-linker "release/codex-cli-linker-linux-arm64"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ runner.os }}-arm64
          path: release/*
          if-no-files-found: error

  release:
    permissions:
      contents: write
    name: Publish GitHub Release
    needs: [build_x64, build_arm]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten artifacts
        run: |
          mkdir -p dist_flat
          find dist -maxdepth 3 -type f -print -exec cp {} dist_flat/ \;

      - name: Read release notes (if present)
        id: notes
        shell: bash
        run: |
          NOTES_PATH="docs/release-notes/${GITHUB_REF_NAME}.md"
          if [ -f "$NOTES_PATH" ]; then
            {
              echo 'RELEASE_BODY<<EOF'
              cat "$NOTES_PATH"
              echo 'EOF'
            } >> "$GITHUB_ENV"
            echo "notes=present" >> "$GITHUB_OUTPUT"
          else
            echo "No release notes at $NOTES_PATH"
            echo "notes=missing" >> "$GITHUB_OUTPUT"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          files: dist_flat/*
          generate_release_notes: true
          body: ${{ env.RELEASE_BODY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
