name: Publish to PyPI

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    # REQUIRED for Trusted Publishing (OIDC)
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build ruff black pytest

      - name: Lint
        run: ruff check .

      - name: Check formatting
        run: black --check .

      - name: Run tests
        run: pytest

      - name: Build distributions
        run: |
          python -m build
        # If your project is in a subdir, add:
        # working-directory: ./path/to/pkg

      - name: Verify artifacts exist
        run: |
          test -d dist && [ -n "$(ls -A dist)" ] || { echo "dist/ is empty"; ls -la; exit 1; }

      - name: Publish to PyPI (Trusted Publisher via OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
        # Do NOT set username/password when using OIDC
        # If using TestPyPI, add:
        # repository-url: https://test.pypi.org/legacy/
