name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build ruff black pytest pytest-cov

      - name: Lint
        run: ruff check .

      - name: Check formatting
        run: black --check .

      - name: Run tests
        run: pytest

      - name: Build distributions
        run: python -m build --outdir dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          files: dist/*
          generate_release_notes: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true

  binary:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: python -m pip install --upgrade pip pyinstaller

      - name: Build binary
        run: pyinstaller codex-cli-linker.py --onefile --name codex-cli-linker-${{ matrix.os }}

      - name: Upload binary release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          files: dist/codex-cli-linker-${{ matrix.os }}*
