name: Release
permissions:
  contents: read

on:
  push:
    tags:
      - "v*"          # e.g., v0.1.0
      - "release-*"   # e.g., release-2025-09-07
  workflow_dispatch: {}

jobs:
  build:
    name: Build binaries (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install pyinstaller

      - name: Build single-file binary
        shell: bash
        run: |
          pyinstaller -F -n codex-cli-linker codex-cli-linker.py
          mkdir -p release
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp dist/codex-cli-linker.exe "release/codex-cli-linker-windows-x64.exe"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp dist/codex-cli-linker "release/codex-cli-linker-macos-x64"
          else
            cp dist/codex-cli-linker "release/codex-cli-linker-linux-x64"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ runner.os }}
          path: release/*
          if-no-files-found: error

  release:
    permissions:
      contents: write
    name: Publish GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten artifacts
        run: |
          mkdir -p dist_flat
          find dist -type f -maxdepth 3 -print -exec cp {} dist_flat/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          files: dist_flat/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
