name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - 'coverage.svg'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'coverage.svg'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install test deps
        run: |
          python -m pip install pytest pytest-cov pytest-timeout coverage-badge
      - name: Run tests (with coverage)
        run: |
          pytest
          python -m coverage xml
      - name: Generate and commit coverage badge
        shell: bash
        run: |
          set -euo pipefail
          coverage-badge -o coverage.svg -f
          if ! git diff --quiet -- coverage.svg; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add coverage.svg
            git commit -m "chore: update coverage badge [skip ci]"
            git push
          else
            echo "coverage.svg unchanged; nothing to commit"
          fi

